### ISSUE TITLE
Add `quiet` as an external dependency

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/cardano-prelude#104]
PR #89 added a `GHC.Generics`-based and `generic-deriving`-based function that derives a `Show` instance that suppresses record selectors (for the record selectors declared in the `data` declaration, not those in nested types, arguments, etc).

The PR input-output-hk/cardano-base#74 to add some initial use-cases of that stalled when @erikd  asked about interop with `Read`. That's when I realized my implicit assumption that the `stock` derivation of `Read` works with or without selectors was wrong! It indeed requires selectors. @erikd suggested https://hackage.haskell.org/package/quiet, which provides both `show` and `read`.

Today, @jonathanknowles asked for a similar function on https://input-output-rnd.slack.com/archives/C48HA39RS/p1584949845136100, so I'm now longer the only person who has so far desired this capability :)

This Issue is to resolve these PRs. Some options:

  * Add `quiet` as an external dependency and revert PR #89.

  * (Strawman) Add a `read` analog to PR #89 (this is dead in the water, since there is no generic `read` defined by `generic-deriving` and we shouldn't start from scratch).

  * (Strawman) Don't expect `Read` instances. `Read` is generally a poor parser and our libraries do not depend on it. However, we devs sometimes do depend on it as a quality-of-life improvement, in the following way. When a QuickCheck tests fails, it dumps the test case's generated values. `read "<CTRL-V>"` let's use copy those values as-is into the test module in order to debug that failure. For example, this mitigates the need for adding a `Data.Map` prefix to `fromList` for each map in the generated values. Moreover, it is an implicit assumption (law even?) that `read . show = id`, so in some sense a mechanism providing a `show` definition that doesn't also offer a corresponding `read` definition is inherently incomplete. (edit: Thomas pointed out input-output-hk/ouroboros-network#861)

**Comment by nfrisby** [comment]
@mrBliss, @erikd, at this point, I think switching to `quiet` makes the most sense (as my "strawman" labels would suggest). Do you agree?

Also, what's the process for gaining consensus on adding a 3rd-party dependency? Does this repo have a code owner to decide that sort of thing? Thanks.

**Comment by mrBliss** [comment]
> @mrBliss, @erikd, at this point, I think switching to `quiet` makes the most sense (as my "strawman" labels would suggest). Do you agree?

I agree. Related to your 2nd strawman argument: https://github.com/input-output-hk/ouroboros-network/issues/861

**Comment by erikd** [comment]
`quiet` is a small library which has a simple well defined function. I can;t see anybody have a problem with this.
