### ISSUE TITLE
heapWords for Integer should return the actual size of the integer

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-prelude#22]
It seems that the idea of `heapWords` is that it returns the actual size of heap words of the given value. If that's correct, then we need to [change this instance](https://github.com/input-output-hk/cardano-prelude/blob/db5deaa1780b3a0811aaa4b8941037c5efa17105/src/Cardano/Prelude/HeapWords.hs#L384).

**Comment by erikd** [comment]
This needs to be done for all variable sized values, including `Natural`, `Integer`, `ByteString`, `Text` and so on, but probably on on an as-needed basis.
