### ISSUE TITLE
versioning?

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-prelude#44]
I was searching for a compatible version of `snapshot.yaml` with `lts-13.6` and `ghc-8.6.3`.
Unfortunately, there is no "release" in GH, nor are there any "tags" set.

How will versioning be setup for this repo?

**Comment by erikd** [comment]
Before release, versioning is done via the git hash. See for instance the `stack.yaml` file in the `cardano-ledger` repo.

**Comment by erikd** [comment]
This has been discussed. Version numbers offer far few guarantees than git hashes so until we want to release this code to Hackage (or similar) git hashes are the way to go.
